version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing tools..."
      - pip install boto3
      - apt-get update -y
      - apt-get install -y jq

  pre_build:
    commands:
      - echo "AppName:$AppName"
      - cd "$AppName" || { echo "ERROR:$AppName folder not found"; exit 1; }
  
      # Find latest dated folder
      - LATEST_DATE=$(ls -d */ | sort -r | head -1 | sed 's#/##')
      - echo "Latest date folder = $LATEST_DATE"
      - cd "$LATEST_DATE" || { echo "ERROR:$LATEST_DATE folder not found"; exit 1; }
  
      # Find first package folder containing app.py
      - PACKAGE_FOLDER=$(find . -maxdepth 2 -type f -name "app.py" | head -1 | xargs dirname)
      - if [ -z "$PACKAGE_FOLDER" ]; then echo "ERROR:app.py not found in $LATEST_DATE"; exit 1; fi
      - echo "Package folder containing app.py:$PACKAGE_FOLDER"
  
      # Full path for Docker build
      - FULL_PATH="$AppName/$LATEST_DATE/$PACKAGE_FOLDER"
      - echo "FULL_PATH for Docker build:$FULL_PATH"
      - echo $FULL_PATH > /tmp/app_path.txt
  
      # Detect framework
      - if grep -qi "streamlit" "$FULL_PATH/requirements.txt"; then APP_TYPE="streamlit"; \
        elif grep -qi "fastapi" "$FULL_PATH/requirements.txt"; then APP_TYPE="fastapi"; \
        else APP_TYPE="flask"; fi
      - echo "Detected Framework:$APP_TYPE"
      - echo $APP_TYPE > /tmp/app_type.txt


  build:
    commands:
      - APP_PATH=$(cat /tmp/app_path.txt)
      - TYPE=$(cat /tmp/app_type.txt)

      - echo "Starting docker build for $TYPE app"
      - docker build --build-arg APP_PATH=$APP_PATH --build-arg APP_TYPE=$TYPE -t $ECR_URL:$CODEBUILD_BUILD_NUMBER .
      - docker push $ECR_URL:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - /tmp/app_path.txt
    - /tmp/app_type.txt
