version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    REGION: ap-south-1
    EKS_CLUSTER: hts-usecase-cluster
    NAMESPACE: boilerapp
    DEPLOYMENT_NAME: boilerapp
    CONTAINER_NAME: boilerapp
    PORT: 8000
    ECR_REPO_URI: 242880561312.dkr.ecr.ap-south-1.amazonaws.com/hts-ai/boilerapp

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

      - REPO_IMAGE="$ECR_REPO_URI:$IMAGE_TAG"

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER

      - echo "Verifying kubectl connectivity..."
      - kubectl get nodes

      - echo "Ensuring namespace exists..."
      - kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_IMAGE .
      - docker push $REPO_IMAGE

  post_build:
    commands:
      - echo "Creating Kubernetes Deployment YAML..."
      - |
        cat <<EOF > deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $DEPLOYMENT_NAME
          namespace: $NAMESPACE
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $DEPLOYMENT_NAME
          template:
            metadata:
              labels:
                app: $DEPLOYMENT_NAME
            spec:
              containers:
                - name: $CONTAINER_NAME
                  image: $REPO_IMAGE
                  ports:
                    - containerPort: $PORT
                  imagePullPolicy: Always
        EOF

      - echo "Applying Deployment..."
      - kubectl apply -f deployment.yaml

      - echo "Creating Service YAML..."
      - |
        cat <<EOF > service.yaml
        apiVersion: v1
        kind: Service
        metadata:
          name: $DEPLOYMENT_NAME-service
          namespace: $NAMESPACE
        spec:
          type: NodePort
          selector:
            app: $DEPLOYMENT_NAME
          ports:
            - port: 80
              targetPort: $PORT
              protocol: TCP
        EOF

      - echo "Applying Service..."
      - kubectl apply -f service.yaml
