version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    EKS_CLUSTER: hts-usecase-cluster
    NAMESPACE: default
    DEPLOYMENT_NAME: boilerapp
    CONTAINER_NAME: hts/hts-ai-usecases
    REGION: ap-south-1
    ECR_REPO_URI: 242880561312.dkr.ecr.ap-south-1.amazonaws.com/hts/hts-ai-usecases

phases:
  pre_build:
    commands:
      - echo "Detecting app type..."
      - |
        if grep -iq "streamlit" requirements.txt; then
          APP_TYPE="streamlit"
          PORT=8501
        elif grep -iq "fastapi" requirements.txt; then
          APP_TYPE="fastapi"
          PORT=8000
        elif grep -iq "flask" requirements.txt; then
          APP_TYPE="flask"
          PORT=8000
        else
          echo "Unknown app type. Defaulting to port 8000"
          APP_TYPE="unknown"
          PORT=8000
        fi
      - echo "App type detected: $APP_TYPE, Port: $PORT"
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - REPO_IMAGE="$ECR_REPO_URI:$IMAGE_TAG"
      - echo "Setting up kubeconfig..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER --region $REGION

  build:
    commands:
      - echo "Building Docker image for $APP_TYPE..."
      - docker build --build-arg APP_PORT=$PORT -t $REPO_IMAGE .
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_IMAGE

  post_build:
    commands:
      - echo "Generating Kubernetes deployment manifest..."
      - |
        cat <<EOF > deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $DEPLOYMENT_NAME
          namespace: $NAMESPACE
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $DEPLOYMENT_NAME
          template:
            metadata:
              labels:
                app: $DEPLOYMENT_NAME
            spec:
              containers:
                - name: $CONTAINER_NAME
                  image: $REPO_IMAGE
                  ports:
                    - containerPort: $PORT
                  imagePullPolicy: Always
        EOF
      - echo "Applying deployment to EKS..."
      - kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE >/dev/null 2>&1
      - |
        if [ $? -eq 0 ]; then
          echo "Updating existing deployment..."
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPO_IMAGE -n $NAMESPACE
        else
          echo "Creating new deployment..."
          kubectl apply -f deployment.yaml -n $NAMESPACE
        fi
      - kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
      - echo "Deployment completed! App running on port $PORT"

artifacts:
  files:
    - '**/*'
