version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing utilities..."
      - pip install boto3 >/dev/null 2>&1
      - apt-get update -y >/dev/null
      - apt-get install -y jq >/dev/null

  pre_build:
    commands:
      - echo "=== Detecting Application Folder ==="

      # Detect folder containing app.py dynamically
      - APP_DIR=$(dirname "$(find . -name app.py | head -n 1)")
      - |
        if [ "$APP_DIR" = "." ]; then 
          APP_DIR="."; 
        fi

      - echo "APP_DIR detected as:$APP_DIR"
      - echo "$APP_DIR" > /tmp/app_path.txt

      # Detect Framework using requirements.txt
      - echo "=== Detecting Framework Type ==="
      - |
        if grep -qi "streamlit" requirements.txt; then
          APP_TYPE="streamlit"
        elif grep -qi "fastapi" requirements.txt; then
          APP_TYPE="fastapi"
        else
          APP_TYPE="flask"
        fi

      - echo "Framework Detected:$APP_TYPE"
      - echo "$APP_TYPE" > /tmp/app_type.txt

      # ECR login
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
          | docker login --username AWS --password-stdin $ECR_URL

  post_build:
    commands:
      - echo "Configuring kubectl..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $CLUSTER_REGION
  
      - echo "Deploying to EKS..."
      - |
        cat <<EOF > k8s.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $APP_NAME
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $APP_NAME
          template:
            metadata:
              labels:
                app: $APP_NAME
          spec:
              containers:
                - name: $APP_NAME
                  image: $ECR_URL:$CODEBUILD_BUILD_NUMBER
                  ports:
                    - containerPort: $DEFAULT_PORT
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: $APP_NAME
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        spec:
          type: LoadBalancer
          ports:
            - port: 80
              targetPort: $DEFAULT_PORT
          selector:
            app: $APP_NAME
        EOF
  
      - kubectl apply -f k8s.yaml
  
      - echo "✅ Deployment triggered!"
      - kubectl get svc $APP_NAME

build:
    commands:
      - APP_PATH=$(cat /tmp/app_path.txt)
      - TYPE=$(cat /tmp/app_type.txt)

      - echo "=== Starting Docker Build ==="
      - echo "App path:$APP_PATH"
      - echo "App type:$TYPE"
      - docker build --build-arg APP_PATH=$APP_PATH --build-arg APP_TYPE=$TYPE -t $ECR_URL:$CODEBUILD_BUILD_NUMBER .
      - echo "=== Pushing Image to ECR ==="
      - docker push $ECR_URL:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - /tmp/app_path.txt
    - /tmp/app_type.txt
