version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing utilities..."
      - pip install boto3 >/dev/null 2>&1
      - apt-get update -y >/dev/null
      - apt-get install -y jq >/dev/null

  pre_build:
    commands:
      - echo "=== Detecting Application Folder ==="

      # Detect folder containing app.py dynamically
      - APP_DIR=$(dirname "$(find . -name app.py | head -n 1)")
      - |
        if [ "$APP_DIR" = "." ]; then 
          APP_DIR="."; 
        fi
      - cd "$APP_DIR" || { echo "ERROR:Unable to enter app directory"; exit 1; }

      - echo "APP_DIR detected as:$APP_DIR"
      - echo "$APP_DIR" > /tmp/app_path.txt

      # Detect Framework using requirements.txt
      - echo "=== Detecting Framework Type ==="
      - |
        if grep -qi "streamlit" requirements.txt; then
          APP_TYPE="streamlit"
        elif grep -qi "fastapi" requirements.txt; then
          APP_TYPE="fastapi"
        else
          APP_TYPE="flask"
        fi

      - echo "Framework Detected:$APP_TYPE"
      - echo "$APP_TYPE" > /tmp/app_type.txt

      # ECR login
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
          | docker login --username AWS --password-stdin $ECR_URL

  build:
    commands:
      - APP_PATH=$(cat /tmp/app_path.txt)
      - TYPE=$(cat /tmp/app_type.txt)

      - echo "=== Starting Docker Build ==="
      - echo "App path:$APP_PATH"
      - echo "App type:$TYPE"

      - docker build \
          --build-arg APP_PATH=$APP_PATH \
          --build-arg APP_TYPE=$TYPE \
          -t $ECR_URL:$CODEBUILD_BUILD_NUMBER .

      - echo "=== Pushing Image to ECR ==="
      - docker push $ECR_URL:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - /tmp/app_path.txt
    - /tmp/app_type.txt
