version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://amazon-eks.s3.amazonaws.com/1.30.0/2024-04-19/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ECR_REPO_URI
      - echo APP_PATH: $APP_PATH
      - echo APP_TYPE: $APP_TYPE

  build:
    commands:
      - echo Building Docker Image...
      - docker build -t $APP_NAME \
          --build-arg APP_PATH=$APP_PATH \
          --build-arg APP_TYPE=$APP_TYPE .
      - docker tag $APP_NAME:latest $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Image...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - echo Deploying to EKS...
      - |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Service
        metadata:
          name: $APP_NAME
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: alb
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        spec:
          type: LoadBalancer
          selector:
            app: $APP_NAME
          ports:
          - port: 80
            targetPort: 8000
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $APP_NAME
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $APP_NAME
          template:
            metadata:
              labels:
                app: $APP_NAME
            spec:
              containers:
              - name: $APP_NAME
                image: $ECR_REPO_URI:$IMAGE_TAG
                ports:
                - containerPort: 8000
        EOF
      - echo "Deployment completed 🚀"
