version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing tools..."
      - pip install boto3
      - apt-get update -y
      - apt-get install -y jq

  pre_build:
    commands:
      - echo "AppName = $AppName"
      
      # Go to the app folder directly (no date folder)
      - cd "$AppName" || { echo "ERROR:Folder $AppName not found"; exit 1; }

      # Since app.py is directly here, set FULL_PATH = $AppName
      - FULL_PATH="$AppName"
      - echo "Using FULL_PATH = $FULL_PATH"
      - echo "$FULL_PATH" > /tmp/app_path.txt

      # Detect APP_TYPE
      - |
        if grep -qi "streamlit" "requirements.txt"; then
            APP_TYPE="streamlit"
        elif grep -qi "fastapi" "requirements.txt"; then
            APP_TYPE="fastapi"
        else
            APP_TYPE="flask"
        fi

      - echo "Detected Framework = $APP_TYPE"
      - echo "$APP_TYPE" > /tmp/app_type.txt

      # Login to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin $ECR_URL

  build:
    commands:
      - APP_PATH=$(cat /tmp/app_path.txt)
      - TYPE=$(cat /tmp/app_type.txt)

      - echo "Starting docker build for $TYPE app"
      - docker build --build-arg APP_PATH=$APP_PATH --build-arg APP_TYPE=$TYPE -t $ECR_URL:$CODEBUILD_BUILD_NUMBER .
      - docker push $ECR_URL:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - /tmp/app_path.txt
    - /tmp/app_type.txt
