version: 0.2

env:
  variables:
    IMAGE_TAG: build-$(date +%s)
    REGION: ap-south-1
    EKS_CLUSTER: hts-usecase-cluster
    NAMESPACE: boilerapp
    DEPLOYMENT_NAME: boilerapp
    CONTAINER_NAME: boilerapp
    PORT: 8000
    ECR_REPO_URI: 242880561312.dkr.ecr.ap-south-1.amazonaws.com/hts-ai/boilerapp
    S3_BUCKET: hts-ai-usecase-links

phases:
  pre_build:
    commands:
      - set -e
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO_URI

      - echo "Setting REPO_IMAGE..."
      - export REPO_IMAGE="$ECR_REPO_URI:$IMAGE_TAG"

      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region $REGION --name $EKS_CLUSTER --kubeconfig kubeconfig.yaml
      - export KUBECONFIG=$PWD/kubeconfig.yaml

      - echo "Verifying kubectl connectivity..."
      - kubectl get nodes

      - echo "Ensuring namespace exists..."
      - kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

  build:
    commands:
      - set -e
      - echo "Building Docker image $REPO_IMAGE..."
      - docker build --no-cache -t $REPO_IMAGE .
      - echo "Pushing Docker image..."
      - docker push $REPO_IMAGE

  post_build:
    commands:
      - set -e
      - echo "Creating Kubernetes Deployment YAML..."
      - |
        cat <<EOF > deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: $DEPLOYMENT_NAME
          namespace: $NAMESPACE
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $DEPLOYMENT_NAME
          template:
            metadata:
              labels:
                app: $DEPLOYMENT_NAME
            spec:
              containers:
                - name: $CONTAINER_NAME
                  image: $REPO_IMAGE
                  ports:
                    - containerPort: $PORT
                  imagePullPolicy: Always
        EOF

      - echo "Applying Deployment..."
      - kubectl apply -f deployment.yaml

      - echo "Creating LoadBalancer Service YAML..."
      - |
        cat <<EOF > service.yaml
        apiVersion: v1
        kind: Service
        metadata:
          name: $DEPLOYMENT_NAME-service
          namespace: $NAMESPACE
        spec:
          type: LoadBalancer
          selector:
            app: $DEPLOYMENT_NAME
          ports:
            - port: 80
              targetPort: $PORT
              protocol: TCP
        EOF

      - echo "Applying Service..."
      - kubectl apply -f service.yaml

      - echo "Waiting for LoadBalancer hostname..."
      - |
        while true; do
          HOSTNAME=$(kubectl get svc $DEPLOYMENT_NAME-service -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [ ! -z "$HOSTNAME" ]; then
            break
          fi
          echo "Waiting for hostname..."
          sleep 10
        done

      - echo "Deployment completed successfully!"
      - echo "Application URL: http://$HOSTNAME"

      - echo "Uploading URL to S3..."
      - echo "http://$HOSTNAME" > app_url.txt
      - aws s3 cp app_url.txt s3://$S3_BUCKET/boilerapp/app_url.txt
